### ISSUE TITLE
[BUG] Lots of Errors

### ISSUE THREAD

**Issue by QueenLunacore** [SparkLinkStudios/portal-but-its-osha-compliant#18]
Doors, reflections, and just stuff is generally missing around the map, like guardrails. What do i need installed?

**Comment by SparkLinkStudios** [comment]
Hi, can you please send some screenshots so I can investigate this issue? Is it the reflection textures being broken? Or are models missing?

**Comment by EluWriter** [comment]
I had that same issue until I downloaded the latest release. I believe the issue happened because of the YouTuber "[Beau Productions - Rip Rip Rip](https://www.youtube.com/@Rip-Rip-Rip)" who uploaded a video about this mod and used a direct link to an earlier release in their video description. So, people go there, download it, play it, and they have no idea it's not the latest release. 

However, even with the latest release, there are problems with missing textures and reflections in the backrooms area. 

![Image](https://github.com/user-attachments/assets/d439f21e-f6e1-4d72-bb15-eabd40af92ee)
![Image](https://github.com/user-attachments/assets/c8c66759-dea6-446d-8658-59e811d9622d)
![Image](https://github.com/user-attachments/assets/3ab7a6bf-31b0-459c-9553-b1c657bb45a0)
![Image](https://github.com/user-attachments/assets/6b18fe4b-f4e4-40a1-a7ca-7a658ba5af1e)

**Comment by SparkLinkStudios** [comment]
The missing textures on the frame around the grating is fixed now in v2.6.2-beta. I couldn't reproduce the second issue yet, I am still investigating it.

**Comment by EluWriter** [comment]
I thought that maybe the issue is because of me using an AMD GPU (RX 6700 XT), so I tried it on my ThinkPad T440p, which has i7-4712MQ CPU and Intel HD 4600 integrated GPU. The issue is still present there. I will see if it's present on a different PC that I have, but it also has AMD graphics (RX 550), and I'll get back with the results in the coming days.
